### ISSUE TITLE
Snapchat API

### ISSUE THREAD

**Issue by h4ck1th4rd** [stoyangenchev/messaging-app#1]
looking for snapchat private API.

skype me at: mzaboss

**Comment by stoyangenchev** [comment]
[https://github.com/mgp25/SC-API](https://github.com/mgp25/SC-API)

I believe this is what you are looking for?

**Comment by h4ck1th4rd** [comment]
Thank you for your reply, It's outdated. not work anymore.

**Comment by stoyangenchev** [comment]
Well unfortunately I can't help you with that. I believe you have to talk to the guys responsible for the Snapchat API package.

Sorry for not being of any help.

**Comment by h4ck1th4rd** [comment]
No worries buddy, Thank you anyway. cheers.

**Comment by stoyangenchev** [comment]
Cheers!
